### ISSUE TITLE
Error: Cannot find module '../lib/tag.js'

### ISSUE THREAD

**Issue by unssnu** [longfei59418888/xl_mock#1]
你好，在运行： xl_mock  start  -p   3000后，抛出该错误

我之前做了这两步：
npm  install  -g  xl_mock
npm  install  -D xl_mock

麻烦大神看下这个启动方式出了什么问题哈。。。？感谢

**Comment by longfei59418888** [comment]
> 你好，在运行： xl_mock start -p 3000后，抛出该错误
> 
> 我之前做了这两步：
> npm install -g xl_mock
> npm install -D xl_mock
> 
> 麻烦大神看下这个启动方式出了什么问题哈。。。？感谢


你先要在全局安装，
然后在项目中安装。
我看看报什么错误？

**Comment by unssnu** [comment]
### 是的，先已经全局安装了
D:\project\openapi-platform\openapi-web>**npm install -g xl_mock**
D:\Users\HOUWEILI925\AppData\Roaming\npm\xl_mock -> D:\Users\HOUWEILI925\AppData\Roaming\npm\node_modules\xl_mock\bin\xl_mock.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\xl_mock\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ xl_mock@1.0.5
updated 1 package in 292.329s

### 然后在项目中也安装了
D:\project\openapi-platform\openapi-web>**npm add xl_mock**
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.

+ xl_mock@1.0.5
added 69 packages from 43 contributors and audited 17396 packages in 22.872s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

### 然后使用命令打开2048端口，就报错了
D:\project\openapi-platform>**xl_mock start -p 2048**
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../lib/tag.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Users\HOUWEILI925\AppData\Roaming\npm\node_modules\xl_mock\bin\xl_mock.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)


我是搜索到您的博客，然后看到很不错，再找到github的哈~~~上面步骤是按照博客中的指南操作的

**Comment by longfei59418888** [comment]
你加我qq吧，我具体了解下

**Comment by longfei59418888** [comment]
398497684

**Comment by longfei59418888** [comment]
改了，去掉xl_mock.js 里面的一句话就ok了。。你看下

**Comment by longfei59418888** [comment]
已经修复好了。。
代码不能利用git管理多人开发，因为存在数据目录的数据文件冲突。
如果想要多人开发，可以修改下
